name: Code Quality Checks

on:
  push:
    branches: [ main, staging, develop ]
  pull_request:
    branches: [ main, staging ]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint --if-present
      
    - name: Run tests
      run: npm test -- --coverage --watchAll=false
      
    - name: Build check
      run: npm run build
      env:
        # Use staging config for build check
        REACT_APP_FIREBASE_PROJECT_ID: tolmantest
        REACT_APP_FIREBASE_API_KEY: test-key
        REACT_APP_FIREBASE_AUTH_DOMAIN: test.firebaseapp.com
        REACT_APP_FIREBASE_DATABASE_URL: https://test.firebaseio.com
        REACT_APP_FIREBASE_STORAGE_BUCKET: test.firebasestorage.app
        REACT_APP_FIREBASE_MESSAGING_SENDER_ID: "123456789"
        REACT_APP_FIREBASE_APP_ID: "1:123456789:web:test"
        REACT_APP_FIREBASE_MEASUREMENT_ID: "G-TEST"
        REACT_APP_GOOGLE_MAPS_API_KEY: test-maps-key
